#!/bin/bash
# Install-for-presure-sensor-Jetson.sh
# Install Air Pressure jetson
# pai-script-id=9729e1er-60d8-42cb-8f01-dcf075b4cbf9
# Created by Eran Caballero on Wed Feb 16 10:20:08 UTC 2022
# Generated by PAI Linux Bot
# Copyrights PAI Tech INC 2022, all rights reserved

#This script contains:

	#Set JETSON specific settings
	#Installs all required packages
	#Setting parameters
	#Installs AIME o/s file system

set -e
# PAI includes

PAI=/var/PAI
PAI_LOGS=$PAI/Logs

# PAI Const
PAI_INSTALLER_NAME="Pai Prepare Air Pressure Project"
GIT_REPO_JETSON_GPIO="https://github.com/NVIDIA/jetson-gpio.git"

# PAI functions

# Validate sudo
if [ $(id -u) -ne 0 ]; then
        printf "Script must be run as root. Try 'sudo ./Install-for-pressure-sensor-Jetson-wget.sh'\n"
        exit 1
fi

pai_9729e1ee-60d8-42cb-8f01-dcf075b4cbf9_intro()
{
	echo -e "\e[91m$PAI_INSTALLER_NAME"
	echo -e "\e[34mInstalling requirments for AirPressureProject"
	echo ""
#	cd Documents
	echo ""

	echo -e "\e[33mInstall Jetson GPIO"
	git clone $GIT_REPO_JETSON_GPIO
	chown -R pai:pai jetson-gpio/
	cd jetson-gpio/
	python3 setup.py install
	cd ..
	cp /home/pai/Documents/jetson-gpio/build/lib/Jetson/GPIO/99-gpio.rules /etc/udev/rules.d/
	udevadm control --reload-rules && sudo udevadm trigger
	usermod -aG gpio pai
	usermod -aG i2c pai
	echo ""

	echo -e "\e[34mInstall libi2c"
	git clone https://github.com/amaork/libi2c.git
	chown -R pai:pai libi2c/
	cd libi2c/
	python3 setup.py install
	cd ..
	echo ""

	echo -e "\e[33mInstall websocket"
	sudo -H pip3 install adafruit-circuitpython-servokit
	pip3 install websocket-client
	echo ""

	echo -e "\e[34mValidates correct connection"
	i2cdetect -y -r 1
	echo ""
	echo -e "\e[1mMake sure you see "'>>>>>76<<<<<'""
	echo ""
	sleep 5

	echo -e "\e[34mImporting Air Pressure Project"
	wget -O /home/pai/Documents/AirPressureProject.tar.gz https://cdn.pai-net.org/pai-cdn/get-file?cdn-key=c7a12501-4fe6-4696-8957-86761f504eab
	tar -xvf AirPressureProject.tar.gz > /dev/null
	chown -R pai:pai AirPressureProject/
	rm AirPressureProject.tar.gz

}

# PAI MAIN FLOW

pai_9729e1ee-60d8-42cb-8f01-dcf075b4cbf9_intro
