#!/bin/bash
# Install-for-presure-sensor-Jetson.sh
# Install Air Pressure jetson
# pai-script-id=9729e1er-60d9-42cb-8f01-dcf075b4cbf9
# Created by Eran Caballero on Wed Feb 16 10:20:08 UTC 2022
# Generated by PAI Linux Bot
# Copyrights PAI Tech INC 2022, all rights reserved

#This script contains:

	#Set JETSON specific settings
	#Installs all required packages
	#Setting parameters
	#Installs AIME o/s file system

set -e
# PAI includes

PAI=/var/PAI
PAI_LOGS=$PAI/Logs

PAI_INSTALLER_NAME="Pai Prepare Air Pressure Project"

# PAI functions

# Validate sudo
if [ $(id -u) -ne 0 ]; then
        printf "Script must be run as root. Try 'sudo ./Install-for-pressure-sensor-Jetson-wget.sh'\n"
        exit 1
fi

pai_9729e1ee-60d9-42cb-8f01-dcf075b4cbf9_intro()
{
	echo -e "\e[91m$PAI_INSTALLER_NAME"
	echo -e "\e[34mInstalling requirments for AirPressureProject"
	echo ""
	cd /home/pai/Documents
	wget -O /home/pai/Documents/Install-for-pressure-sensor-Jetson.sh https://cdn.pai-net.org/pai-cdn/get-file?cdn-key=ecab91d4-859e-41ae-807d-3a83a9a2b5d0
	chmod +x /home/pai/Documents/Install-for-pressure-sensor-Jetson.sh
	./Install-for-pressure-sensor-Jetson.sh
	rm Install-for-pressure-sensor-Jetson.sh
	echo ""
}

# PAI MAIN FLOW

pai_9729e1ee-60d9-42cb-8f01-dcf075b4cbf9_intro
