#!/bin/bash
# pai-install-jetson-gpio-pythom.sh
# Install GPIO library for python on NVIDIA Jetson AGX NX Nano 
# pai-script-id=9729e1er-60d9-42cb-8f01-dcf075b4cbf9
# Created by Eran Caballero on Wed Feb 16 10:20:08 UTC 2022
# Generated by PAI Linux Bot
# Copyrights PAI Tech INC 2022, all rights reserved
# www.pai-tech.org

#This script contains:

# Set JETSON specific settings
# Installs all required packages
# Setting parameters

set -e
# PAI includes

PAI=/var/PAI
PAI_LOGS=$PAI/Logs

PAI_INSTALLER_NAME="Jetson GPIO Python lib installer"

# PAI functions

# Validate sudo
if [ $(id -u) -ne 0 ]; then
        printf "Script must be run as root. Try 'sudo ./Install-for-pressure-sensor-Jetson-wget.sh'\n"
        exit 1
fi

pai_9729e1ee-60d9-42cb-8f01-dcf075b4cbf9_intro()
{
	echo -e "\e[91m$PAI_INSTALLER_NAME"
	echo -e "\e[34mInstalling Jetson GPIO library for python"
	echo ""
	DEFAULT_FOLDER="/var/PAI/Apps/"
	read -p "Select installation folder "
	cd /home/pai/Documents
	wget -O /home/pai/Documents/Install-for-pressure-sensor-Jetson.sh https://cdn.pai-net.org/pai-cdn/get-file?cdn-key=ecab91d4-859e-41ae-807d-3a83a9a2b5d0
	chmod +x /home/pai/Documents/Install-for-pressure-sensor-Jetson.sh
	./Install-for-pressure-sensor-Jetson.sh
	rm Install-for-pressure-sensor-Jetson.sh
	echo ""
}

# PAI MAIN FLOW

pai_9729e1ee-60d9-42cb-8f01-dcf075b4cbf9_intro
